DocWorks for js-wixcode-sdk - 18 changes detected, but 13 issue detected changes: Service $w.UploadButton has changed summary Service $w.UploadButton has changed description Service $w.UploadButton.examples[0] has changed body Service $w.UploadButton.examples[0] has changed extra.description Service $w.UploadButton property fileType has changed summary Service $w.UploadButton property fileType has changed description Service $w.UploadButton property fileType.examples[0] has changed body Service $w.UploadButton property value has changed description Service $w.UploadButton property value.examples[0] has changed body Service $w.UploadButton property value.examples[1] has changed body Service $w.UploadButton property value.examples[1] has changed extra.description Service $w.UploadButton operation startUpload has changed summary Service $w.UploadButton operation startUpload.examples[1] has changed body Service $w.UploadButton operation startUpload.examples[1] has changed extra.description Service $w.UploadButton message File.examples[0] has changed body Service $w.UploadButton message UploadedFile member width has changed doc Service $w.UploadButton message UploadedFile member height has changed doc Service $w.UploadButton message UploadedFile has a new member duration
issues:
Property zoom is missing a type annotation (GoogleMap.es6 (235))
Property center is defined two or more times (GoogleMap.es6 (159, 194))
Property zoom is defined two or more times (GoogleMap.es6 (211, 235))
Property markers has mismatching types for get ($w.GoogleMap.markers) and set ($w.GoogleMap) (GoogleMap.es6 (107, 142))
Operation postMessage has an unknown param type * (HtmlComponent.es6 (143))
Property data has an unknown type * (HtmlComponentMessageEvent.es6 (26))
Operation routerSitemap has an unknown return type wix-router.WixRouterSitemapEntry (site.es6 (101))
Callback GoogleMapClickEvent is defined two or more times (GoogleMapClickEvent.es6 (4, 10))
Property value has an unknown type * (ValueMixin.es6 (56))
Property value has an unknown type * (ValueMixin.es6 (84))
ERROR: The @description tag requires a value. File: document.es6, line: 106
ERROR: The @snippet tag - file 'examples/Window-scrollTo_without_animation' not found. File: window.es6 line: 383
ERROR: The @snippet tag - file 'examples/Window-scrollTo_without_animation' not found. File: window.es6 line: 391